version: 2.1
orbs:
  slack: sandbox/slack@dev:0.2.30
 #testing without webhook
jobs:
  build:
    docker: 
      - image: circleci/node
    steps:
      - run: exit 0
      - slack/notify:
          message: testing message sending