version: 2.1

orbs:
  slack: sandbox/slack@dev:0.2

jobs:
  build:
    docker: 
      - image: circleci/node
    steps:
      - run: |
          sudo apt-get install jq
          SLACK_BUILD_DATA=$(curl -s https://circleci.com/api/v1.1/project/github/KyleTryon/SlackOrbTest/10?circle-token=${CIRCLECI_TOKEN})
          echo fetched build data
          SLACK_BUILD_STATUS=$(echo "${SLACK_BUILD_DATA}" | jq '.status')
          if [ "$SLACK_CIRCLECI_STATUS" == "success" ]
            then
              echo "sucessful job"
            else
              echo Issue with job "$SLACK_BUILD_STATUS"
          fi