version: 2.1
orbs:
  slack: sandbox/slack@1.1.0
jobs:
  build:
    docker: 
      - image: circleci/node
    steps:
      - run: exit 0 #toggle this to force success or status for testing
      - slack/status