version: 2.1

orbs:
  slack: sandbox/slack@dev:0.2

jobs:
  build:
    docker: 
      - image: circleci/node
    steps:
      - run: |
          sudo apt-get install jq
          curl https://circleci.com/api/v1.1/project/github/KyleTryon/SlackOrbTest/10?circle-token=`$CIRCLECI_TOKEN` | jq '.status'