version: 2.1

orbs:
  slack: techsquidtv/slack@dev:0.1

build:
  docker: circleci/node
  steps:
    - slack/message:
      webhook: https://hooks.slack.com/services/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
      message: Good news!
