version: 2.1

orbs:
  slack: sandbox/slack@dev:0.2

jobs:
  build:
    docker: 
      - image: circleci/node
    steps:
      - slack/notify:
          webhook: https://hooks.slack.com/services/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
          message: testing
