version: 2.1

orbs:
  slack: sandbox/slack@dev:0.2.5

jobs:
  build:
    docker: 
      - image: circleci/node
    steps:
      - slack/notify:
          message: testing env var in parameters. This test is for notify/webhook
          #removed webhook