version: 2.1
  #resubmit again
orbs:
  slack: sandbox/slack@dev:1.2.0

jobs:
  notifytest:
    docker: 
      - image: circleci/node
    steps:
      - run: exit 0 #toggle this to force success or status for testing
      - slack/notify:
          mentions: "USLACKBOT,USER1,USER2,USER3"

  statustest:
    docker: 
      - image: circleci/node
    steps:
      - run: exit 0 #toggle this to force success or status for testing
      - slack/status:
          mentions: "USLACKBOT,USER1,USER2,USER3"

workflows:
  TestSlack:
    jobs:
      - notifytest
      - statustest